import { useState } from 'react'
import { Play, ShieldCheck } from 'lucide-react'
import { ErrorState, LoadingState, Panel, Status } from '../components/common'
import { useApi } from '../hooks/useApi'
import { api } from '../services/api'
import type { PolicyDecision, PolicyRequest } from '../types/api'

const experiments: PolicyRequest[] = [
  { message_type: 'FLIGHT_CONTROL', criticality: 'ROUTINE', threat_level: 'NORMAL', latency_budget_ms: 1000 },
  { message_type: 'FLIGHT_CONTROL', criticality: 'IMPORTANT', threat_level: 'ELEVATED', latency_budget_ms: 500 },
  { message_type: 'FLIGHT_CONTROL', criticality: 'CRITICAL', threat_level: 'HIGH', latency_budget_ms: 1000 },
  { message_type: 'FLIGHT_CONTROL', criticality: 'SAFETY_CRITICAL', threat_level: 'CRITICAL', latency_budget_ms: 500 },
  { message_type: 'FLIGHT_CONTROL', criticality: 'SAFETY_CRITICAL', threat_level: 'CRITICAL', latency_budget_ms: 100 },
]

export function Policy() {
  const profiles = useApi(api.policyProfiles), rules = useApi(api.policyRules), metrics = useApi(api.policyMetrics)
  const [input, setInput] = useState<PolicyRequest>({ message_type: 'FLIGHT_CONTROL', criticality: 'SAFETY_CRITICAL', threat_level: 'HIGH', latency_budget_ms: 500 })
  const [decision, setDecision] = useState<PolicyDecision | null>(null), [error, setError] = useState<string | null>(null), [busy, setBusy] = useState(false), [experimentResults, setExperimentResults] = useState<PolicyDecision[]>([])
  const evaluate = async () => { setBusy(true); setError(null); try { setDecision(await api.evaluatePolicy(input)); void metrics.reload() } catch (e) { setError(e instanceof Error ? e.message : 'POLICY EVALUATION FAILED') } finally { setBusy(false) } }
  const runExperiments = async () => { setBusy(true); setError(null); try { const results = await Promise.all(experiments.map(item => api.evaluatePolicy(item))); setExperimentResults(results); void metrics.reload() } catch (e) { setError(e instanceof Error ? e.message : 'EXPERIMENT EXECUTION FAILED') } finally { setBusy(false) } }
  if (profiles.loading || rules.loading) return <LoadingState label="RETRIEVING POLICY CONFIGURATION…" />
  if (profiles.error || rules.error) return <ErrorState message={profiles.error ?? rules.error ?? 'POLICY API CONNECTION FAILED'} />
  return <>
    <div className="page-heading"><h1>ADAPTIVE CRYPTOGRAPHIC POLICY</h1><p>Safety-constrained selection using measured Phase 6 hybrid-handshake performance. Simulation / research prototype.</p></div>
    <div className="two-col"><Panel title="POLICY INPUT"><div className="form-grid policy-input"><label>MESSAGE TYPE<select value={input.message_type} onChange={e => setInput({ ...input, message_type: e.target.value })}><option>FLIGHT_CONTROL</option><option>ALTITUDE</option><option>HEADING</option><option>AIRCRAFT_STATUS</option><option>NAVIGATION_UPDATE</option></select></label><label>CRITICALITY<select value={input.criticality} onChange={e => setInput({ ...input, criticality: e.target.value })}>{['ROUTINE', 'IMPORTANT', 'CRITICAL', 'SAFETY_CRITICAL'].map(item => <option key={item}>{item}</option>)}</select></label><label>THREAT LEVEL<select value={input.threat_level} onChange={e => setInput({ ...input, threat_level: e.target.value })}>{['NORMAL', 'ELEVATED', 'HIGH', 'CRITICAL'].map(item => <option key={item}>{item}</option>)}</select></label><label>LATENCY BUDGET (MS)<input type="number" min="1" value={input.latency_budget_ms} onChange={e => setInput({ ...input, latency_budget_ms: Number(e.target.value) })} /></label></div><button className="primary" onClick={() => void evaluate()} disabled={busy}>{busy ? 'EVALUATING…' : 'EVALUATE POLICY'}</button></Panel><Panel title="CURRENT SESSION METRICS">{metrics.data ? <div className="summary-row"><Metric label="EVALUATIONS" value={metrics.data.total_evaluations} /><Metric label="SELECTED" value={metrics.data.successful_selections} /><Metric label="CONFLICTS" value={metrics.data.constraint_conflicts} /><Metric label="BLOCKED DOWNGRADES" value={metrics.data.blocked_downgrades} /></div> : <LoadingState label="RETRIEVING CURRENT SESSION METRICS…" />}</Panel></div>
    {error && <ErrorState message={error} />}
    <Panel title="DECISION"><Decision decision={decision} /></Panel>
    <div className="two-col"><Panel title="DETERMINISTIC REASON">{decision ? <div className="policy-reason">{decision.reason}</div> : <div className="state">EVALUATE A POLICY REQUEST TO VIEW THE DETERMINISTIC DECISION REASON.</div>}</Panel><Panel title="CONSTRAINT CHECK">{decision ? <div className="constraint-list">{decision.constraints.map(item => <div key={item.name}><Status value={item.passed ? 'PASS' : 'FAIL'} good={item.passed} /><strong>{item.name}</strong><span>{item.detail}</span></div>)}</div> : <div className="state">NO POLICY DECISION AVAILABLE</div>}</Panel></div>
    <Panel title="DECISION TRACE"><div className="decision-trace">{['INPUT', 'CRITICALITY ANALYSIS', 'THREAT ANALYSIS', 'SAFETY FILTERING', 'BENCHMARK EVALUATION', 'PROFILE SCORING', 'FINAL DECISION'].map((stage, index) => <div key={stage}><span>{String(index + 1).padStart(2, '0')}</span><strong>{stage}</strong><Status value={decision ? 'COMPLETE' : 'IDLE'} good={!!decision} /></div>)}</div></Panel>
    <Panel title="APPROVED PROFILE COMPARISON"><table><thead><tr><th>PROFILE</th><th>ASSURANCE</th><th>KEY ESTABLISHMENT</th><th>AUTHENTICATION</th><th>AEAD</th><th>MEASURED LATENCY</th><th>ALLOWED CRITICALITY</th><th>DOWNGRADE</th></tr></thead><tbody>{profiles.data?.map(profile => <tr key={profile.profile_id}><td><strong>{profile.profile_id}</strong></td><td>{profile.assurance_level}</td><td>{profile.key_agreement} + {profile.kem}</td><td>{profile.authentication}</td><td>{profile.aead}</td><td>{profile.measured_latency_ms?.toFixed(4) ?? 'UNAVAILABLE'} ms</td><td>{profile.allowed_criticality.join(', ')}</td><td>{profile.downgrade_allowed ? 'ALLOWED' : 'PROHIBITED'}</td></tr>)}</tbody></table></Panel>
    <div className="two-col"><Panel title="SAFETY POLICY"><div className="rule-list">{rules.data?.safety_rules.map(rule => <div key={rule}><ShieldCheck size={14} />{rule}</div>)}</div></Panel><Panel title="SCORING CONFIGURATION"><div className="result-list">{Object.entries(rules.data?.scoring_weights ?? {}).map(([name, value]) => <div className="result-line" key={name}><span>{name.toUpperCase()} WEIGHT</span><strong>{value}</strong></div>)}</div></Panel></div>
    <Panel title="CONTROLLED EXPERIMENTS" action={<button className="secondary pipeline-action" onClick={() => void runExperiments()} disabled={busy}><Play size={13} />{busy ? 'RUNNING…' : 'RUN EXPERIMENTS'}</button>}>{experimentResults.length ? <table><thead><tr><th>INPUT</th><th>PROFILE</th><th>SCORE</th><th>LATENCY</th><th>DECISION</th><th>DOWNGRADE</th><th>REASON</th></tr></thead><tbody>{experimentResults.map((item, index) => <tr key={index}><td>{experiments[index].criticality} / {experiments[index].threat_level} / {experiments[index].latency_budget_ms} ms</td><td>{item.selected_profile ?? 'NONE'}</td><td>{item.score ?? 'N/A'}</td><td>{item.estimated_latency_ms?.toFixed(4) ?? 'N/A'} ms</td><td><Status value={item.status} good={item.status === 'PROFILE_SELECTED'} /></td><td>{item.downgrade_blocked ? 'BLOCKED' : 'NOT REQUIRED'}</td><td>{item.reason}</td></tr>)}</tbody></table> : <div className="state">RUN EXPERIMENTS TO GENERATE REAL POLICY-ENGINE RESULTS.</div>}</Panel>
  </>
}

function Metric({ label, value }: { label: string; value: number }) { return <div><small>{label}</small><strong>{value}</strong></div> }
function Decision({ decision }: { decision: PolicyDecision | null }) { if (!decision) return <div className="state">NO DECISION EVALUATED</div>; return <div className="summary-row policy-decision"><div><small>SELECTED PROFILE</small><strong>{decision.selected_profile ?? 'NONE'}</strong></div><div><small>ASSURANCE</small><strong>{decision.assurance_level ?? 'N/A'}</strong></div><div><small>SCORE</small><strong>{decision.score ?? 'N/A'}</strong></div><div><small>LATENCY / BUDGET</small><strong>{decision.estimated_latency_ms?.toFixed(4) ?? 'N/A'} / {decision.latency_budget_ms} ms</strong></div><div><small>STATUS</small><Status value={decision.status} good={decision.status === 'PROFILE_SELECTED'} /></div></div> }
